### ISSUE TITLE
Please update this library to use RFC 8188 Content encoding spec

### ISSUE THREAD

**Issue by jrconlin** [SherClockHolmes/webpush-go#16]
First off, thanks for this library. 

[RFC 8188](https://datatracker.ietf.org/doc/rfc8188/?include_text=1) has been out for a while, and services will soon start deprecating the "aesgcm" encoding type. The differences aren't that much (the salt is included in the data prefix, and the nonce phrases changed to reflect the new content encoding schema).

Thanks!

**Comment by SherClockHolmes** [comment]
@jrconlin Thanks for the heads up, I'll try to get to this soon-ish.

**Comment by jrconlin** [comment]
Sorry for the late reply, but thanks for doing this!
