### ISSUE TITLE
Not passing a vapidPublicKey should return an error

### ISSUE THREAD

**Issue by hzr** [SherClockHolmes/webpush-go#22]
`options.vapidPublicKey` is sent directly to `getVAPIDAuthorizationHeader()`, but is never validated, so when not passing it, the Authorization header ends up with `k=`. It would be useful if this returned an error.

**Comment by SherClockHolmes** [comment]
I haven't decided if validation should be handled by the library or the consumer before passing in (technically you will get a status code like `401` in the HTTP response). I would be interested in what preference people have.
