### ISSUE TITLE
applicationServerKey not valid

### ISSUE THREAD

**Issue by trayanr** [SherClockHolmes/webpush-go#25]
I tried to generate the key with the `GenerateVAPIDKeys()` function. When subscribing the error `applicationServerKey is not valid` showed up. I managed to get it working but with a public key of length 88 chars. The generated from the `GenerateVAPIDKeys` is only 44.

**Comment by trayanr** [comment]
I also receive an error if the privateKey contains `+ = /`. Also another error. This may not be related but when I have a private key that doesn't include these characters and the request is sent to fcm.googleapi.... I get 403 forbidden.

**Comment by SherClockHolmes** [comment]
Hey @trayanr, I'm not quite sure about your specific issue. I do have a test for checking the length of the public and private key generation. I recommend checking out the repo and validating if you can reproduce it there first. Closing this for now.
