### ISSUE TITLE
panic on pad

### ISSUE THREAD

**Issue by danf0rth** [SherClockHolmes/webpush-go#27]
In some cases the panic occurred when called `SendNotification` method.

`go version go1.12.1 linux/amd64`
also tried
`go version go1.12.5 linux/amd64`

```
runtime.gopanic
        /usr/local/go/src/runtime/panic.go:522
runtime.panicmakeslicelen
        /usr/local/go/src/runtime/slice.go:27
runtime.makeslice
        /usr/local/go/src/runtime/slice.go:44
github.com/SherClockHolmes/webpush-go.pad
        /home/danforth/Dev/go/pkg/mod/github.com/!sher!clock!holmes/webpush-go@v1.1.0/webpush.go:250
github.com/SherClockHolmes/webpush-go.SendNotification
        /home/danforth/Dev/go/pkg/mod/github.com/!sher!clock!holmes/webpush-go@v1.1.0/webpush.go:169

```

**Comment by gbhrdt** [comment]
I think I've seen something similar when using a too big payload.

**Comment by danf0rth** [comment]
@gbhrdt yes, just yesterday we tried to reduce our payloads and bug is gone. Today we try to increase payload again and the problem still not appears, moreover, our payloads now is even bigger then before, when the panic occurs.

**Comment by pierrre** [comment]
I also have this issue:
- webpush-go version: v1.0.1 (I'll try to upgrade)
- Go version: 1.12.1

For now, I will defer/recover the panic in my code.
