### ISSUE TITLE
Option to skip padding

### ISSUE THREAD

**Issue by vikramj74** [SherClockHolmes/webpush-go#35]
I tested this library on a different browsers and observed that firefox mobile is not able to handle a payload of standard 4KB size. To work around this problem, I disabled the padding in the source code. I would appreciate it if there was a way to turn off the padding option, for such cases.

**Comment by SherClockHolmes** [comment]
Hey @vikramj74,

There isn't an option to skip padding, but you can limit the size of the record for Firefox mobile in the Options struct: https://github.com/SherClockHolmes/webpush-go/blob/master/webpush.go#L42

**Comment by decademoon** [comment]
Is the padding necessary?
