### ISSUE TITLE
tag prefix "v" for Go module

### ISSUE THREAD

**Issue by pierrre** [SherClockHolmes/webpush-go#36]
Can you add tag prefix "v" on the most recent tags ?
I think it's required for Go modules.
See https://pkg.go.dev/github.com/SherClockHolmes/webpush-go?tab=versions
The recent versions are not detected.

**Comment by SherClockHolmes** [comment]
Thanks for catching that. I re-released both versions.

**Comment by pierrre** [comment]
thank you !
