### ISSUE TITLE
Push notification not delivered on Firefox

### ISSUE THREAD

**Issue by Arsaev** [SherClockHolmes/webpush-go#38]
Using code from example and it works with chrome, but now with firefox.
`webpush.SendNotification` dose not return any error. Program finish as if everything worked correctly.

**Comment by Arsaev** [comment]
my  mistake. Double check endpoint URLs

**Comment by dhinojosac** [comment]
> Using code from example and it works with chrome, but now with firefox. `webpush.SendNotification` dose not return any error. Program finish as if everything worked correctly.

Could you help me with this https://github.com/SherClockHolmes/webpush-go/issues/21#issuecomment-975547100 please! Thanks in advance!
