### ISSUE TITLE
HTTP 406 from Edge

### ISSUE THREAD

**Issue by gbhrdt** [SherClockHolmes/webpush-go#40]
Hi,

it might not be directly related to this library, but since yesterday we are getting HTTP 406 responses from nearly all Edge subscriptions.
Did anyone experience something similar?

**Comment by YasinY** [comment]
Hello,
these issues may help out debugging/finding out what could be the cause.

https://github.com/web-push-libs/web-push-php/issues/335
https://github.com/web-push-libs/webpush-java/issues/175

**Comment by gbhrdt** [comment]
Microsoft seems to have fixed it.
