### ISSUE TITLE
send push message to ios return 403

### ISSUE THREAD

**Issue by ennnnzo** [SherClockHolmes/webpush-go#61]
It works for me to send push message to `https://fcm.googleapis.com/fcm/send/`

But if send to `https://web.push.apple.com/` returns  `403`

```
 {"reason":"BadJwtToken"}
```

**Comment by ennnnzo** [comment]
I just didnt set subscriber in options.If set , It works.

**Comment by leomorpho** [comment]
Indeed! Thanks for posting this as I was completely puzzled as to why it was working on desktop but not iOS!
```go
resp, err := webpush.SendNotification([]byte(message), &pushSub, &webpush.Options{
			Subscriber:      "the-email-of-your-platform-sending-the-push-notif@test.com",
			VAPIDPublicKey:  vapidPublicKey,
			VAPIDPrivateKey: vapidPrivateKey,
		})
```
