### ISSUE TITLE
no push received

### ISSUE THREAD

**Issue by BigBoulard** [SherClockHolmes/webpush-go#65]
Hi,

I wrote the below code that seems to work pretty well.

The frontend sends a subscription in the database, and then the backend gets it and sends a push.
I get a 200 status code, no errors but I don't receive any push.

I've tested the service-worker in my sveltekit app and the push handler works too (chrome > service worker > push payload)

```go
sub := &webpush.Subscription{
	Endpoint: pushSub.PushSubscription.Endpoint,
	Keys: webpush.Keys{
		P256dh: conf.PushVAPIDKeys.Public,
		Auth:   conf.PushVAPIDKeys.Private,
	},
}
spew.Dump(sub)

// Send Notification
resp, err := webpush.SendNotification([]byte(push.Msg), sub, &webpush.Options{
	Subscriber:      push.FirstName,
	VAPIDPublicKey:  sub.Keys.P256dh,
	VAPIDPrivateKey: sub.Keys.Auth,
	TTL:             30,
})
if err != nil {
	return  fmt.Errorf("error_sending_notification %w", err)
}
defer resp.Body.Close()
```

I subscribed a fake user through Chrome and Firefox, and the subscriptions look like this:

```sh
(*webpush.Subscription)(0x140000b3ec0)({
 Endpoint: (string) (len=234) "https://updates.push.services.mozilla.com/wpush/v2/XXX",
 Keys: (webpush.Keys)
  Auth: (string) (len=43) "awCf-XXX",
  P256dh: (string) (len=87) "BC_Q-XXX"
 }
})
(*webpush.Subscription)(0x140002bef00)({
 Endpoint: (string) (len=188) "https://fcm.googleapis.com/fcm/send/XXX",
 Keys: (webpush.Keys) {
  Auth: (string) (len=43) "awCf-XXX",
  P256dh: (string) (len=87) "BC_Q-XXX"
 }
})
```

I feel like I'm missing something obvious...
Do I need to create a project for my application in FCM (Firebase Cloud Messaging) and provide some sort of credentials?

**Comment by BigBoulard** [comment]
got mix up with the service worker subscription keys and the vapid keys

**Comment by 0x0elliot** [comment]
there should be errors if this doesn't work out. not sure if this is a library level issue or an API level issue.
