### ISSUE TITLE
SendNotification returns nil error value in error case

### ISSUE THREAD

**Issue by EmpireJones** [SherClockHolmes/webpush-go#7]
There is at least one case in the SendNotification function of webpush.go in which a nil error value may be returned in an error state:
```
	// Shared secret
	publicKeyX, publicKeyY := elliptic.Unmarshal(curve, clientPublicKey)
	if publicKeyY == nil {
		return &http.Response{}, err
	}
```

A new error should be returned for this case; otherwise, the consuming project may incorrectly assume that the Response is valid.

Additionally, the comments from elliptic.Unmarshal indicate that the x value would be null in the case of an error, but this code is checking the y value. This may or may not be ok to do.

**Comment by SherClockHolmes** [comment]
Thanks again @EmpireJones, I have pushed a fix to master.
